#rename enigma data to be the same as abcd - is there a more effective way????
##write a function within this function to change left to right and then apply to existing dataset-- TRY

renameFUN <- function(data){
  
  tmp.file = data 
  
  tmp.file = tmp.file %>% 
    mutate (annotations = ifelse(tmp.file$V1 == "Left medial orbitofrontal cortex","lh.mobfr",
                                 ifelse(tmp.file$V1 == "Left rostral anterior cingulate cortex", "lh.rracate",
                                        ifelse(tmp.file$V1 == "Left fusiform gyrus", "lh.fusiform",
                                               ifelse(tmp.file$V1 == "Left insula", "lh.insula",
                                                      ifelse(tmp.file$V1 == "Left isthmus cingulate cortex", "lh.ihcate",
                                                             ifelse(tmp.file$V1 == "Left posterior cingulate cortex", "lh.ptcate",
                                                                    ifelse(tmp.file$V1 == "Left middle temporal gyrus", "lh.mdtm",
                                                                           ifelse(tmp.file$V1 == "Left pars orbitalis", "lh.parsobis",
                                                                                  ifelse(tmp.file$V1 == "Left parahippocampal gyrus", "lh.parahpal",
                                                                                         ifelse(tmp.file$V1 == "Left superior frontal gyrus", "lh.sufr",
                                                                                                ifelse(tmp.file$V1 == "Left inferior parietal cortex", "lh.ifpl",
                                                                                                       ifelse(tmp.file$V1 == "Left pars opercularis", "lh.parsopc",
                                                                                                              ifelse(tmp.file$V1 == "Left banks superior temporal sulcus", "lh.bankssts",
                                                                                                                     ifelse(tmp.file$V1 == "Left hemisphere average thickness", "lh.mean",
                                                                                                                            ifelse(tmp.file$V1 == "Left pars triangularis", "lh.parstgris",
                                                                                                                                   ifelse(tmp.file$V1 == "Left inferior temporal gyrus", "lh.iftm",
                                                                                                                                          ifelse(tmp.file$V1 == "Left lateral orbitofrontal cortex", "lh.lobfr",
                                                                                                                                                 ifelse(tmp.file$V1 == "Left supramarginal gyrus", "lh.sm",
                                                                                                                                                        ifelse(tmp.file$V1 == "Left caudal anterior cingulate cortex", "lh.cdacate",
                                                                                                                                                               ifelse(tmp.file$V1 == "Left entorhinal cortex", "lh.ehinal",
                                                                                                                                                                      ifelse(tmp.file$V1 == "Left rostral middle frontal gyrus", "lh.rrmdfr",
                                                                                                                                                                             ifelse(tmp.file$V1 == "Left transverse temporal gyrus", "lh.trvtm",
                                                                                                                                                                                    ifelse(tmp.file$V1 == "Left precuneus", "lh.pc",
                                                                                                                                                                                           ifelse(tmp.file$V1 == "Left lateral occipital cortex", "lh.locc",
                                                                                                                                                                                                  ifelse(tmp.file$V1 == "Left precentral gyrus", "lh.precn",
                                                                                                                                                                                                         ifelse(tmp.file$V1 == "Left caudal middle frontal gyrus", "lh.cdmdfr",
                                                                                                                                                                                                                ifelse(tmp.file$V1 == "Left frontal pole", "lh.frpole",
                                                                                                                                                                                                                       ifelse(tmp.file$V1 == "Left superior parietal cortex", "lh.supl",
                                                                                                                                                                                                                              ifelse(tmp.file$V1 == "Left paracentral lobule", "lh.paracn",
                                                                                                                                                                                                                                     ifelse(tmp.file$V1 == "Left lingual gyrus", "lh.lingual",
                                                                                                                                                                                                                                            ifelse(tmp.file$V1 == "Left temporal pole", "lh.tmpole",
                                                                                                                                                                                                                                                   ifelse(tmp.file$V1 == "Left postcentral gyrus", "lh.postcn",
                                                                                                                                                                                                                                                          ifelse(tmp.file$V1 == "Left cuneus", "lh.cuneus",
                                                                                                                                                                                                                                                                 ifelse(tmp.file$V1 == "Left pericalcarine cortex", "lh.pericc",
                                                                                                                                                                                                                                                                        ifelse(tmp.file$V1 == "Left superior temporal gyrus", "lh.sutm",
                                                                                                                                                                                                                                                                               ifelse(tmp.file$V1 == "Left hemisphere total surface area", "lh.total",NA)))))))))))))))))))))))))))))))))))))
  
  new.data <- tmp.file %>% 
    mutate (annotations = ifelse(tmp.file$V1 == "Right medial orbitofrontal cortex","rh.mobfr",
                                 ifelse(tmp.file$V1 == "Right rostral anterior cingulate cortex", "rh.rracate",
                                        ifelse(tmp.file$V1 == "Right fusiform gyrus", "rh.fusiform",
                                               ifelse(tmp.file$V1 == "Right insula", "rh.insula",
                                                      ifelse(tmp.file$V1 == "Right isthmus cingulate cortex", "rh.ihcate",
                                                             ifelse(tmp.file$V1 == "Right posterior cingulate cortex", "rh.ptcate",
                                                                    ifelse(tmp.file$V1 == "Right middle temporal gyrus", "rh.mdtm",
                                                                           ifelse(tmp.file$V1 == "Right pars orbitalis", "rh.parsobis",
                                                                                  ifelse(tmp.file$V1 == "Right parahippocampal gyrus", "rh.parahpal",
                                                                                         ifelse(tmp.file$V1 == "Right superior frontal gyrus", "rh.sufr",
                                                                                                ifelse(tmp.file$V1 == "Right inferior parietal cortex", "rh.ifpl",
                                                                                                       ifelse(tmp.file$V1 == "Right pars opercularis", "rh.parsopc",
                                                                                                              ifelse(tmp.file$V1 == "Right banks superior temporal sulcus", "rh.bankssts",
                                                                                                                     ifelse(tmp.file$V1 == "Right hemisphere average thickness", "rh.mean",
                                                                                                                            ifelse(tmp.file$V1 == "Right pars triangularis", "rh.parstgris",
                                                                                                                                   ifelse(tmp.file$V1 == "Right inferior temporal gyrus", "rh.iftm",
                                                                                                                                          ifelse(tmp.file$V1 == "Right lateral orbitofrontal cortex", "rh.lobfr",
                                                                                                                                                 ifelse(tmp.file$V1 == "Right supramarginal gyrus", "rh.sm",
                                                                                                                                                        ifelse(tmp.file$V1 == "Right caudal anterior cingulate cortex", "rh.cdacate",
                                                                                                                                                               ifelse(tmp.file$V1 == "Right entorhinal cortex", "rh.ehinal",
                                                                                                                                                                      ifelse(tmp.file$V1 == "Right rostral middle frontal gyrus", "rh.rrmdfr",
                                                                                                                                                                             ifelse(tmp.file$V1 == "Right transverse temporal gyrus", "rh.trvtm",
                                                                                                                                                                                    ifelse(tmp.file$V1 == "Right precuneus", "rh.pc",
                                                                                                                                                                                           ifelse(tmp.file$V1 == "Right lateral occipital cortex", "rh.locc",
                                                                                                                                                                                                  ifelse(tmp.file$V1 == "Right precentral gyrus", "rh.precn",
                                                                                                                                                                                                         ifelse(tmp.file$V1 == "Right caudal middle frontal gyrus", "rh.cdmdfr",
                                                                                                                                                                                                                ifelse(tmp.file$V1 == "Right frontal pole", "rh.frpole",
                                                                                                                                                                                                                       ifelse(tmp.file$V1 == "Right superior parietal cortex", "rh.supl",
                                                                                                                                                                                                                              ifelse(tmp.file$V1 == "Right paracentral lobule", "rh.paracn",
                                                                                                                                                                                                                                     ifelse(tmp.file$V1 == "Right lingual gyrus", "rh.lingual",
                                                                                                                                                                                                                                            ifelse(tmp.file$V1 == "Right temporal pole", "rh.tmpole",
                                                                                                                                                                                                                                                   ifelse(tmp.file$V1 == "Right postcentral gyrus", "rh.postcn",
                                                                                                                                                                                                                                                          ifelse(tmp.file$V1 == "Right cuneus", "rh.cuneus",
                                                                                                                                                                                                                                                                 ifelse(tmp.file$V1 == "Right pericalcarine cortex", "rh.pericc",
                                                                                                                                                                                                                                                                        ifelse(tmp.file$V1 == "Right superior temporal gyrus", "rh.sutm",
                                                                                                                                                                                                                                                                               ifelse(tmp.file$V1 == "Right hemisphere total surface area", "rh.total",tmp.file$annotations)))))))))))))))))))))))))))))))))))))
  return(new.data)
}

