renameFUN <- function(data){
  
  tmp.file = data 
  
  tmp.file = tmp.file %>% 
    mutate(annotations = ifelse(tmp.file$V1 == "Left medial orbitofrontal cortex","lh.medialorbitofrontal",
                                 ifelse(tmp.file$V1 == "Left rostral anterior cingulate cortex", "lh.rostralanteriorcingulate",
                                        ifelse(tmp.file$V1 == "Left fusiform gyrus", "lh.fusiform",
                                               ifelse(tmp.file$V1 == "Left insula", "lh.insula",
                                                      ifelse(tmp.file$V1 == "Left isthmus cingulate cortex", "lh.isthmuscingulate",
                                                             ifelse(tmp.file$V1 == "Left posterior cingulate cortex", "lh.posteriorcingulate",
                                                                    ifelse(tmp.file$V1 == "Left middle temporal gyrus", "lh.middletemporal",
                                                                           ifelse(tmp.file$V1 == "Left pars orbitalis", "lh.parsorbitalis",
                                                                                  ifelse(tmp.file$V1 == "Left parahippocampal gyrus", "lh.parahippocampal",
                                                                                         ifelse(tmp.file$V1 == "Left superior frontal gyrus", "lh.superiorfrontal",
                                                                                                ifelse(tmp.file$V1 == "Left inferior parietal cortex", "lh.inferiorparietal",
                                                                                                       ifelse(tmp.file$V1 == "Left pars opercularis", "lh.parsopercularis",
                                                                                                              ifelse(tmp.file$V1 == "Left banks superior temporal sulcus", "lh.bankssts",
                                                                                                                     ifelse(tmp.file$V1 == "Left hemisphere average thickness", "lh.AvgCT",
                                                                                                                            ifelse(tmp.file$V1 == "Left pars triangularis", "lh.parstriangularis",
                                                                                                                                   ifelse(tmp.file$V1 == "Left inferior temporal gyrus", "lh.inferiortemporal",
                                                                                                                                          ifelse(tmp.file$V1 == "Left lateral orbitofrontal cortex", "lh.lateralorbitofrontal",
                                                                                                                                                 ifelse(tmp.file$V1 == "Left supramarginal gyrus", "lh.supramarginal",
                                                                                                                                                        ifelse(tmp.file$V1 == "Left caudal anterior cingulate cortex", "lh.caudalanteriorcingulate",
                                                                                                                                                                      ifelse(tmp.file$V1 == "Left rostral middle frontal gyrus", "lh.rostralmiddlefrontal",
                                                                                                                                                                             ifelse(tmp.file$V1 == "Left transverse temporal gyrus", "lh.transversetemporal",
                                                                                                                                                                                    ifelse(tmp.file$V1 == "Left precuneus", "lh.precuneus",
                                                                                                                                                                                           ifelse(tmp.file$V1 == "Left lateral occipital cortex", "lh.lateraloccipital",
                                                                                                                                                                                                  ifelse(tmp.file$V1 == "Left precentral gyrus", "lh.precentral",
                                                                                                                                                                                                         ifelse(tmp.file$V1 == "Left caudal middle frontal gyrus", "lh.caudalmiddlefrontal",
                                                                                                                                                                                                                ifelse(tmp.file$V1 == "Left frontal pole", "lh.frontalpole",
                                                                                                                                                                                                                       ifelse(tmp.file$V1 == "Left superior parietal cortex", "lh.superiorparietal",
                                                                                                                                                                                                                              ifelse(tmp.file$V1 == "Left paracentral lobule", "lh.paracentral",
                                                                                                                                                                                                                                     ifelse(tmp.file$V1 == "Left lingual gyrus", "lh.lingual",
                                                                                                                                                                                                                                            ifelse(tmp.file$V1 == "Left temporal pole", "lh.temporalpole",
                                                                                                                                                                                                                                                   ifelse(tmp.file$V1 == "Left postcentral gyrus", "lh.postcentral",
                                                                                                                                                                                                                                                          ifelse(tmp.file$V1 == "Left cuneus", "lh.cuneus",
                                                                                                                                                                                                                                                                 ifelse(tmp.file$V1 == "Left pericalcarine cortex", "lh.pericalcarine",
                                                                                                                                                                                                                                                                        ifelse(tmp.file$V1 == "Left superior temporal gyrus", "lh.superiortemporal",
                                                                                                                                                                                                                                                                               ifelse(tmp.file$V1 == "Left hemisphere total surface area", "lh.AvgCSA",
                                                                                                                                                                                                                                                                                             ifelse(tmp.file$V1 == "Left entorhinal cortex", "lh.entorhinal",NA)))))))))))))))))))))))))))))))))))))
  
  new.data <- tmp.file %>% 
    mutate(annotations = ifelse(tmp.file$V1 == "Right medial orbitofrontal cortex","rh.medialorbitofrontal",
                                 ifelse(tmp.file$V1 == "Right rostral anterior cingulate cortex", "rh.rostralanteriorcingulate",
                                        ifelse(tmp.file$V1 == "Right fusiform gyrus", "rh.fusiform",
                                               ifelse(tmp.file$V1 == "Right insula", "rh.insula",
                                                      ifelse(tmp.file$V1 == "Right isthmus cingulate cortex", "rh.isthmuscingulate",
                                                             ifelse(tmp.file$V1 == "Right posterior cingulate cortex", "rh.posteriorcingulate",
                                                                    ifelse(tmp.file$V1 == "Right middle temporal gyrus", "rh.middletemporal",
                                                                           ifelse(tmp.file$V1 == "Right pars orbitalis", "rh.parsorbitalis",
                                                                                  ifelse(tmp.file$V1 == "Right parahippocampal gyrus", "rh.parahippocampal",
                                                                                         ifelse(tmp.file$V1 == "Right superior frontal gyrus", "rh.superiorfrontal",
                                                                                                ifelse(tmp.file$V1 == "Right inferior parietal cortex", "rh.inferiorparietal",
                                                                                                       ifelse(tmp.file$V1 == "Right pars opercularis", "rh.parsopercularis",
                                                                                                              ifelse(tmp.file$V1 == "Right banks superior temporal sulcus", "rh.bankssts",
                                                                                                                     ifelse(tmp.file$V1 == "Right hemisphere average thickness", "rh.AvgCT",
                                                                                                                     ifelse(tmp.file$V1 == "Right pars triangularis", "rh.parstriangularis",
                                                                                                                            ifelse(tmp.file$V1 == "Right inferior temporal gyrus", "rh.inferiortemporal",
                                                                                                                                   ifelse(tmp.file$V1 == "Right lateral orbitofrontal cortex", "rh.lateralorbitofrontal",
                                                                                                                                          ifelse(tmp.file$V1 == "Right supramarginal gyrus", "rh.supramarginal",
                                                                                                                                                 ifelse(tmp.file$V1 == "Right caudal anterior cingulate cortex", "rh.caudalanteriorcingulate",
                                                                                                                                                        ifelse(tmp.file$V1 == "Right rostral middle frontal gyrus", "rh.rostralmiddlefrontal",
                                                                                                                                                               ifelse(tmp.file$V1 == "Right transverse temporal gyrus", "rh.transversetemporal",
                                                                                                                                                                      ifelse(tmp.file$V1 == "Right precuneus", "rh.precuneus",
                                                                                                                                                                             ifelse(tmp.file$V1 == "Right lateral occipital cortex", "rh.lateraloccipital",
                                                                                                                                                                                    ifelse(tmp.file$V1 == "Right precentral gyrus", "rh.precentral",
                                                                                                                                                                                           ifelse(tmp.file$V1 == "Right caudal middle frontal gyrus", "rh.caudalmiddlefrontal",
                                                                                                                                                                                                  ifelse(tmp.file$V1 == "Right frontal pole", "rh.frontalpole",
                                                                                                                                                                                                         ifelse(tmp.file$V1 == "Right superior parietal cortex", "rh.superiorparietal",
                                                                                                                                                                                                                ifelse(tmp.file$V1 == "Right paracentral lobule", "rh.paracentral",
                                                                                                                                                                                                                       ifelse(tmp.file$V1 == "Right lingual gyrus", "rh.lingual",
                                                                                                                                                                                                                              ifelse(tmp.file$V1 == "Right temporal pole", "rh.temporalpole",
                                                                                                                                                                                                                                     ifelse(tmp.file$V1 == "Right postcentral gyrus", "rh.postcentral",
                                                                                                                                                                                                                                            ifelse(tmp.file$V1 == "Right cuneus", "rh.cuneus",
                                                                                                                                                                                                                                                   ifelse(tmp.file$V1 == "Right pericalcarine cortex", "rh.pericalcarine",
                                                                                                                                                                                                                                                          ifelse(tmp.file$V1 == "Right superior temporal gyrus", "rh.superiortemporal",
                                                                                                                                                                                                                                                                 ifelse(tmp.file$V1 == "Right hemisphere total surface area", "rh.AvgCSA",
                                                                                                                                                                                                                                                                 ifelse(tmp.file$V1 == "Right entorhinal cortex", "rh.entorhinal",tmp.file$annotations)))))))))))))))))))))))))))))))))))))

return(new.data)
}

